export interface WordPair {
  word: string
  echo: string
}

const WORD_PAIRS: WordPair[] = [
  { word: 'Apple', echo: 'Pear' },
  { word: 'Dog', echo: 'Wolf' },
  { word: 'Car', echo: 'Truck' },
  { word: 'Cat', echo: 'Lion' },
  { word: 'Chair', echo: 'Stool' },
  { word: 'Coffee', echo: 'Tea' },
  { word: 'Rain', echo: 'Snow' },
  { word: 'River', echo: 'Lake' },
  { word: 'House', echo: 'Cabin' },
  { word: 'City', echo: 'Town' },
  { word: 'Ocean', echo: 'Sea' },
  { word: 'Mountain', echo: 'Hill' },
  { word: 'Forest', echo: 'Jungle' },
  { word: 'Desert', echo: 'Tundra' },
  { word: 'Guitar', echo: 'Ukulele' },
  { word: 'Piano', echo: 'Keyboard' },
  { word: 'Basketball', echo: 'Volleyball' },
  { word: 'Soccer', echo: 'Football' },
  { word: 'Bicycle', echo: 'Scooter' },
  { word: 'Train', echo: 'Subway' },
  { word: 'Boat', echo: 'Ship' },
  { word: 'Airplane', echo: 'Helicopter' },
  { word: 'Sun', echo: 'Star' },
  { word: 'Moon', echo: 'Satellite' },
  { word: 'Fire', echo: 'Lava' },
  { word: 'Ice', echo: 'Frost' },
  { word: 'Gold', echo: 'Silver' },
  { word: 'Diamond', echo: 'Ruby' },
  { word: 'Crown', echo: 'Tiara' },
  { word: 'Key', echo: 'Lock' },
  { word: 'Door', echo: 'Window' },
  { word: 'Bridge', echo: 'Tunnel' },
  { word: 'Tower', echo: 'Castle' },
  { word: 'Garden', echo: 'Park' },
  { word: 'Library', echo: 'Museum' },
  { word: 'School', echo: 'University' },
  { word: 'Bread', echo: 'Cake' },
  { word: 'Cheese', echo: 'Butter' },
  { word: 'Wine', echo: 'Juice' },
  { word: 'Chocolate', echo: 'Caramel' },
  { word: 'Pizza', echo: 'Calzone' },
  { word: 'Burger', echo: 'Sandwich' },
  { word: 'Salad', echo: 'Soup' },
  { word: 'Sushi', echo: 'Ramen' },
  { word: 'Clock', echo: 'Watch' },
  { word: 'Map', echo: 'Compass' },
  { word: 'Book', echo: 'Scroll' },
  { word: 'Pen', echo: 'Pencil' },
  { word: 'Camera', echo: 'Telescope' },
  { word: 'Phone', echo: 'Radio' },
  { word: 'Computer', echo: 'Calculator' },
  { word: 'Lamp', echo: 'Candle' },
  { word: 'Blanket', echo: 'Towel' },
  { word: 'Pillow', echo: 'Cushion' },
  { word: 'Mirror', echo: 'Glass' },
  { word: 'Arrow', echo: 'Spear' },
  { word: 'Shield', echo: 'Armor' },
  { word: 'Crystal', echo: 'Gem' },
  { word: 'Feather', echo: 'Wing' },
  { word: 'Nest', echo: 'Cave' },
  { word: 'Storm', echo: 'Hurricane' },
  { word: 'Fog', echo: 'Mist' },
  { word: 'Dawn', echo: 'Dusk' },
  { word: 'Shadow', echo: 'Silhouette' },
  { word: 'Echo', echo: 'Reverb' },
  { word: 'Whisper', echo: 'Murmur' },
  { word: 'Laughter', echo: 'Smile' },
  { word: 'Dream', echo: 'Nightmare' },
  { word: 'Memory', echo: 'Diary' },
  { word: 'Maze', echo: 'Labyrinth' },
  { word: 'Puzzle', echo: 'Riddle' },
  { word: 'Treasure', echo: 'Artifact' },
  { word: 'Wand', echo: 'Staff' },
  { word: 'Spell', echo: 'Curse' },
  { word: 'Dragon', echo: 'Phoenix' },
  { word: 'Knight', echo: 'Samurai' },
  { word: 'Wizard', echo: 'Alchemist' },
  { word: 'Ghost', echo: 'Spirit' },
  { word: 'Butterfly', echo: 'Moth' },
  { word: 'Eagle', echo: 'Hawk' },
  { word: 'Owl', echo: 'Raven' },
  { word: 'Dolphin', echo: 'Whale' },
  { word: 'Shark', echo: 'Barracuda' },
  { word: 'Rabbit', echo: 'Hare' },
  { word: 'Fox', echo: 'Coyote' },
  { word: 'Bear', echo: 'Boar' },
  { word: 'Penguin', echo: 'Puffin' },
  { word: 'Swan', echo: 'Goose' },
  { word: 'Parrot', echo: 'Macaw' },
  { word: 'Lobster', echo: 'Crab' },
  { word: 'Octopus', echo: 'Squid' },
  { word: 'Coral', echo: 'Anemone' },
  { word: 'Rose', echo: 'Tulip' },
  { word: 'Oak', echo: 'Maple' },
  { word: 'Pine', echo: 'Spruce' },
  { word: 'Bamboo', echo: 'Sugar Cane' },
  { word: 'Cotton', echo: 'Linen' },
  { word: 'Silk', echo: 'Satin' },
  { word: 'Wool', echo: 'Fur' },
  { word: 'Leather', echo: 'Suede' },
  { word: 'Clay', echo: 'Mud' },
  { word: 'Stone', echo: 'Pebble' },
  { word: 'Sand', echo: 'Dust' },
  { word: 'Ash', echo: 'Soot' },
  { word: 'Steam', echo: 'Smoke' },
  { word: 'Bubble', echo: 'Foam' },
  { word: 'Wave', echo: 'Tide' },
  { word: 'Glacier', echo: 'Iceberg' },
  { word: 'Volcano', echo: 'Geyser' },
  { word: 'Earthquake', echo: 'Avalanche' },
  { word: 'Tornado', echo: 'Cyclone' },
  { word: 'Rainbow', echo: 'Aurora' },
  { word: 'Comet', echo: 'Meteor' },
  { word: 'Prism', echo: 'Kaleidoscope' },
]

export function getRandomWordPair(): WordPair {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)]
}
